### PR TITLE
feat: Added custom transition object support

### PR DESCRIPTION
**Pull request by fatihsolhan**
This feature will allow us to define custom transition object.

Tailwind example:

```vue
<template>
  <vue-final-modal
    :transition="{
      'enter-active-class': 'transition duration-200 ease-in-out transform',
      'enter-class': 'translate-y-full',
      'enter-to-class': 'translate-y-0',
      'leave-active-class': 'transition duration-200 ease-in-out transform',
      'leave-to-class': 'translate-y-full',
      'leave-class': 'translate-y-0'
    }"
  >
    ...modal content
  </vue-final-modal>
</template>
```

transition-gif

### CODE REVIEW

**Comment by hunterliu1003** [comment]
Hi @fatihsolhan 

Thanks for your work that make vue-final-modal much better. 

I’m so busy this week, I will merge the PR on the weekend and will release a new version next week.

It will be perfect if you can send another PR to branch v3 which supports for Vue 3.

🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

@Mini-ghost,
Please help me to confirm if there is nothing missing here.

**Review by hunterliu1003 — APPROVED** [review]

**Comment by hunterliu1003** [comment]
Hi @fatihsolhan,

The PR has released in [v2.1.0](https://github.com/vue-final/vue-final-modal/releases/tag/v2.1.0)

**Comment by hunterliu1003** [comment]
Hi @fatihsolhan,

I just start merge the PR into branch `v3` for Vue 3.
Hope you haven't started it.

**Comment by fatihsolhan** [comment]
> Hi @fatihsolhan,
> 
> 
> 
> I just start merge the PR into branch `v3` for Vue 3.
> 
> Hope you haven't started it.

Hi @hunterliu1003
I started yesterday but there was an issue which transition wasn't working correctly. But I was a bit busy and couldn't continue to working on it. Please let me know if you see same issue

**Comment by hunterliu1003** [comment]
@fatihsolhan,

Thank you very much for your help again.
I will do the rest part.

**Comment by Roxas92** [comment]
> > Hi @fatihsolhan,
> > I just start merge the PR into branch `v3` for Vue 3.
> > Hope you haven't started it.
> 
> Hi @hunterliu1003
> I started yesterday but there was an issue which transition wasn't working correctly. But I was a bit busy and couldn't continue to working on it. Please let me know if you see same issue

@fatihsolhan Is the issue you are talking about related to the entry transition? Haven't seen your PR and tried to get an object configuration working as well but I became desperate because the entry transition isn't working :D So I was wondering if you face the same issue.

**Comment by fatihsolhan** [comment]
> > > Hi @fatihsolhan,
> 
> > > I just start merge the PR into branch `v3` for Vue 3.
> 
> > > Hope you haven't started it.
> 
> > 
> 
> > Hi @hunterliu1003
> 
> > I started yesterday but there was an issue which transition wasn't working correctly. But I was a bit busy and couldn't continue to working on it. Please let me know if you see same issue
> 
> 
> 
> @fatihsolhan Is the issue you are talking about related to the entry transition? Haven't seen your PR and tried to get an object configuration working as well but I became desperate because the entry transition isn't working :D So I was wondering if you face the same issue.

Hi @Roxas92 
No, my issue was not related to entry transition.
If you are using Vue3, please be sure you are using `enter-from-class` instead of `enter-class`
It changed with Vue3

**Comment by hunterliu1003** [comment]
Hi @Roxas92,

Sorry for published the Vue 3 version of the issue for `transition object` late.

Now you can upgrade vue-final-modal to [v3.1.0](https://www.npmjs.com/package/vue-final-modal/v/3.1.0) for `transition object`

**Pull request merged**
