### PR TITLE
docs: suggestions for clarifications dynamic modals

### PR DESCRIPTION
**Pull request by mesqueeb**
feel free to revert what you don't like!

### CODE REVIEW

**Comment by mesqueeb** [comment]
@hunterliu1003 I only used the "edit docs" button of the V2 docs

I checked V3, but I think it's a bit different? The Dynamic Modals page in the V3 docs is together with other API stuff inside a single "API" page.

Is there no requirement for `ModalsContainer` for dynamic modals in V3?

**Comment by hunterliu1003** [comment]
> @hunterliu1003 I only used the "edit docs" button of the V2 docs
> 
> I checked V3, but I think it's a bit different? The Dynamic Modals page in the V3 docs is together with other API stuff inside a single "API" page.
> 
> Is there no requirement for `ModalsContainer` for dynamic modals in V3?

It's a bug. V3 is still needs to use `ModalsContainer` for dynamic modals.
I just fixed the docs and published it.

**Comment by hunterliu1003** [comment]
And I also fixed the "edit docs" button link to the v3 branch.

**Comment by hunterliu1003** [comment]
Thanks a lot~
the new version of docs already released.

**Pull request merged**
